# Generated by Django 5.1.4 on 2025-01-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full name')),
                ('typed', models.CharField(help_text='Type Like This -> Designer, Developer, Freelancer, Photographer', max_length=255, verbose_name='typed')),
                ('about_me', models.CharField(max_length=255, verbose_name='Home About me')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=15)),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('linkedIn', models.URLField(verbose_name='LinkedIn')),
                ('github', models.URLField(verbose_name='Github')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('image', models.ImageField(upload_to='profile/', verbose_name='About Profile')),
            ],
        ),
    ]
